//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funds
    {
        public int Funds_id { get; set; }
        public decimal SendAmount { get; set; }
        public int SendCurrency { get; set; }
        public decimal ReceiveAmount { get; set; }
        public int ReceiveCurrency { get; set; }
        public decimal Rate { get; set; }
        public System.Guid Remittance_Id { get; set; }
    
        public virtual Remittance Remittance { get; set; }
    }
}
