//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remittance_state_log
    {
        public int Remittance_state_log1 { get; set; }
        public System.Guid Remittance_Id { get; set; }
        public int c_status_id { get; set; }
        public Nullable<System.DateTime> datetime_modify { get; set; }
    
        public virtual c_status c_status { get; set; }
        public virtual Remittance Remittance { get; set; }
    }
}
